<footer>
  <section class="footer-main container">
    <div>
      <h3>Blok 1</h3>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium,
      totam rem aperiam eaque ipsa quae.
    </div>
    <div>
      <h3>Blok 2</h3>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium,
      totam rem aperiam eaque ipsa quae.
    </div>
    <div>
      <h3>Blok 3</h3>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium,
      totam rem aperiam eaque ipsa quae.
    </div>
    <div>
      <h3>Blok 4</h3>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium,
      totam rem aperiam eaque ipsa quae.
    </div>
  </section>
  <section class="footer-copyright">
    <div class="container">
      <h3>&copy; <?= date("Y") ?> JoNi</h3><a href="https://validator.w3.org/nu/?doc=<?= $_SERVER["HTTP_HOST"] ?>"
                                              target="_blank"><img alt="W3C Validated"
                                                                   src="../images/vhtml-blue.gif"></a> <a
        href="https://jigsaw.w3.org/css-validator/check/referer" target="_blank"><img alt="Valid CSS!"
                                                                                      src="../images/vcss-blue.gif"></a>
      <a href="http://wave.webaim.org/report#/<?= $_SERVER["HTTP_HOST"] ?>" target="_blank"><img alt="Valid CSS!"
                                                                                                 src="../images/vcss-blue.gif"></a>
    </div>
  </section>
</footer>
</body>
</html>
