<?php include("Partials/header.phtml") ?>
<div class="container aboutus-stats">
  <figure>
    <span class="lnr lnr-code">
      <h5>2000 regels code</h5>
    </span>
  </figure>
  <figure>
    <span class="lnr lnr-bug">
      <h5><span class="strike">geen</span> veel bugs</h5>
    </span>
  </figure>
  <figure>
    <span class="lnr lnr-coffee-cup">
       <h5>300+ kopjes koffie</h5>
    </span>
  </figure>
  <figure>
    <span class="lnr lnr-clock">
        <h5>80+ uur</h5>
      </span>
  </figure>
</div>


<div class="main-container container aboutus">
  <main>
    <h1>Over ons</h1>
    <ul>
      <li>
        <section>
          <img alt="Nick Hartjes" src="/images/NickHartjes.png">
        </section>
        <section>
          <h2>Nick Hartjes</h2>
          <h3>Software developer & DevOps Engineer @ Alliander n.v.</h3>
          <p>
            Een ex-leger man bij EXE, na een maand ‘in dienst’ voelt het nog steeds surreëel. Nick is een self made IT-er, maar houdt in zijn vrije tijd gelukkig nog steeds de oostgrens van ons land in de gaten. Hij is ontzettend gretig om zijn kennis te delen, en daar is nogal veel van. Pas daarom op dat je IT vragen alleen aan hem stelt als je ook de tijd hebt om te horen welke alternatieven ook beschikbaar zijn en wat daar de voor- en nadelen van zijn. Tussendoor weet Nick alle IT ontwikkelingen ontzettend te versnellen. Dit wist hij al te doen voordat hij eigenlijk begreep waar hij aan werkte. Mocht je nog op zoek zijn naar tips voor een goddelijk lichaam: bij defensie was Nick sportinstructeur. Doe er je voordeel mee!
          </p>
        </section>
        <section class="aboutus-progress">
          <ul>
            <li>
              <h4>HTML5</h4>
              <div class="progress progress-90"></div>
            </li>
            <li>
              <h4>CSS</h4>
              <div class="progress progress-80"></div>
            </li>
            <li>
              <h4>PHP</h4>
              <div class="progress progress-70"></div>
            </li>
            <li>
              <h4>Bad Humor</h4>
              <div class="progress progress-100"></div>
            </li>
          </ul>
        </section>
      </li>
      <li>
        <section>
          <img alt="Joey Stoffels" src="/images/JoeyStoffels.png">
        </section>
        <section>
          <h2>Joey Stoffels</h2>
          <h3>Software developer & Commercial Pilot @ Alliander n.v.</h3>
          <p>
            Joey ziet ze vliegen. Niet omdat ie gek is, maar omdat hij piloot was. Dit bleek echter niet een heel lucratieve business dus daarom is hij maar bij EXE komen werken, een startup die al twee jaar verlies draait. Joey kijkt graag series en is daarnaast Nintendo-gekkie, dus voor het volgende EXE uitje zijn we uitgenodigd voor een Mario Kart toernooi bij hem thuis in Elst. Daarnaast is hij fanatiek recreatief badmintonner. Gunstig neveneffect hiervan voor zijn werk als IT developer is dat hij zijn code in ieder geval uit één losse pols klopt. Overigens gaat dit niet altijd helemaal soepel: Joey heeft af en toe last van een ongewillige laptop, dus als hij kaal begint te worden ligt het daaraan.
          </p>
        </section>
        <section>
          <ul>
            <li>
              <h4>HTML5</h4>
              <div class="progress progress-90"></div>
            </li>
            <li>
              <h4>CSS</h4>
              <div class="progress progress-80"></div>
            </li>
            <li>
              <h4>PHP</h4>
              <div class="progress progress-70"></div>
            </li>
            <li>
              <h4>Java</h4>
              <div class="progress progress-80"></div>
            </li>
          </ul>
        </section>
      </li>
    </ul>


  </main>
</div>
<?php include("Partials/footer.phtml") ?>
