<?php include("Partials/header.phtml") ?>
<div class="container aboutus-stats">
  <figure>
    <span class="lnr lnr-code">
      <h5>2000 regels code</h5>
    </span>
  </figure>
  <figure>
    <span class="lnr lnr-bug">
      <h5><span class="strike">geen</span> veel bugs</h5>
    </span>
  </figure>
  <figure>
    <span class="lnr lnr-coffee-cup">
       <h5>300+ kopjes koffie</h5>
    </span>
  </figure>
  <figure>
    <span class="lnr lnr-clock">
        <h5>80+ uur</h5>
      </span>
  </figure>
</div>


<div class="main-container container aboutus">
  <main>
    <h1>Over ons</h1>
    <ul>
      <li>
        <section>
          <img src="http://via.placeholder.com/500x500">
        </section>
        <section>
          <h2>Nick Hartjes</h2>
          <h3>Software developer & DevOps Engineer @ Alliander n.v.</h3>
          <p>
            Yuccie snackwave bespoke tattooed. Disrupt XOXO cloud bread quinoa, taiyaki wolf shaman raclette. Seitan
            asymmetrical pop-up poke direct trade shabby chic forage. Tousled occupy stumptown banh mi DIY knausgaard.
            Taiyaki everyday carry authentic raclette vice YOLO tousled scenester try-hard. Beard viral godard, squid
            hell
            of 90's celiac trust fund cred edison bulb direct trade pork belly.
          </p>
        </section>
        <section class="aboutus-progress">
          <ul>
            <li>
              <h3>HTML5</h3>
              <div class="progress progress-90"></div>
            </li>
            <li>
              <h3>CSS</h3>
              <div class="progress progress-80"></div>
            </li>
            <li>
              <h3>PHP</h3>
              <div class="progress progress-70"></div>
            </li>
            <li>
              <h3>Java</h3>
              <div class="progress progress-80"></div>
            </li>
          </ul>
        </section>
      </li>
      <li>
        <section>
          <img src="http://via.placeholder.com/500x500">
        </section>
        <section>
          <h2>Joey Stoffels</h2>
          <h3>Software developer & Commercial Pilot @ Alliander n.v.</h3>
          <p>
            Yuccie snackwave bespoke tattooed. Disrupt XOXO cloud bread quinoa, taiyaki wolf shaman raclette. Seitan
            asymmetrical pop-up poke direct trade shabby chic forage. Tousled occupy stumptown banh mi DIY knausgaard.
            Taiyaki everyday carry authentic raclette vice YOLO tousled scenester try-hard. Beard viral godard, squid
            hell
            of 90's celiac trust fund cred edison bulb direct trade pork belly.
          </p>
        </section>
        <section>
          <ul>
            <li>
              <h3>HTML5</h3>
              <div class="progress progress-90"></div>
            </li>
            <li>
              <h3>CSS</h3>
              <div class="progress progress-80"></div>
            </li>
            <li>
              <h3>PHP</h3>
              <div class="progress progress-70"></div>
            </li>
            <li>
              <h3>Java</h3>
              <div class="progress progress-80"></div>
            </li>
          </ul>
        </section>
      </li>
    </ul>


  </main>
</div>
<?php include("Partials/footer.phtml") ?>
