<?php include("Partials/header.phtml") ?>
<div class="main-container container cart">
  <main>
    <h1>Winkelwagen</h1>
    <?= (isset($_SESSION['addToCartError'])) ? "<p class='inputError'>".$_SESSION['addToCartError']."</p>" : ''; ?>
    <br>
    <section>
      <?= $cartItemsHtml ?>
    </section>
  </main>
  <aside>
    <form action="/payment" method="post">
      <h2>Overzicht</h2>
      <p>Subtotaal: <span>&euro; <?= number_format($subTotal, 2, ',', '') ?></span></p>
      <p>Verzendkosten:  <span>&euro; <?= number_format($verzendkosten, 2, ',', '') ?></span></p>
      <p><strong>Totaal:  <span>&euro; <?= number_format($totalPrice, 2, ',', '') ?></span></strong></p>
      <input type="hidden" value="<?= $totalPrice ?>" name="totalPrice">
      <button type="submit" value="afrekenen" name="Afrekenen">Afrekenen</button>
    </form>
  </aside>

</div>
<?php include("Partials/footer.phtml") ?>
