<?= include("Partials/header.phtml") ?>



<div class="main-container container">
    <aside>
        <h1>Winkelwagen</h1>
    </aside>
    <main>
        <section>
            <?=cart?>
<!--            <article>-->
<!--                <p>GameTitle</p>-->
<!--                <div class="product-thumb">-->
<!--                    <a href = "#" >-->
<!--                        <img alt = "Secondary image of the article" class="product-back-img" src = "http://via.placeholder.com/480x480/666666/898989">-->
<!--                        <img alt = "Primary image of the article" class="product-front-img" src = "/images/games/$game->image">-->
<!--                    </a>-->
<!--                </div>-->
<!--                <div class="product-action">-->
<!--                    <a class="button add-to-cart" href = "#"> Add to Cart </a > <a class="button" href = "#"><span-->
<!--                                class="lnr lnr-heart"></span ><span class="button-text" > Add to Wishlist </span></a > <a-->
<!--                            class="button" href = "#"><span class="lnr lnr-magnifier" ></span><span class="button-text"> Go to Article </span></a>-->
<!--                </div>-->
<!--            </article>-->
        </section>
    </main>
</div>


<?= include("Partials/footer.phtml") ?>
