<?php include("Partials/header.phtml") ?>

<img class="gameBackgroundImage" alt="<?= $game["title"] ?>" src="/images/games/<?= $gameBackgroundImage ?>">
<div class="main-container container game-detail">
  <h1><?= $game["title"] ?></h1>

  <section>

    <img alt="<?= $game["title"] ?>" src="/images/games/<?= $game["image"] ?>">
    <?= $game["details"] ?>
    <form action="/cart/add/<?= $game["id"] ?>" method="post" class="priceAndSupply">
      <span class="tag">&euro; <?= $game["price"] ?></span>
      <select name="amount">
        <option>1</option>
        <option>2</option>
        <option>3</option>
        <option>4</option>
        <option>5</option>
        <option>6</option>
        <option>7</option>
        <option>8</option>
        <option>9</option>
        <option>10</option>
      </select>
      <button class="button" type="submit">
        <span class="lnr lnr-cart"></span>+
      </button>
      Voorraad: <?= $game["supply"] ?>

    </form>

    <h3>Details:</h3>
    <ul class="details">
      <li><strong>Platform</strong> <?= $game["platform"] ?></li>
      <li><strong>Developer</strong> <?= $game["developer"] ?></li>
      <li><strong>Publisher</strong> <?= $game["publisher"] ?></li>
      <li><strong>Gesproken</strong> <?= $game["languageSpoken"] ?></li>
      <li><strong>Geschreven</strong> <?= $game["languageText"] ?></li>
    </ul>
  </section>
</div>
<?php include("Partials/footer.phtml") ?>
