<?php include("Partials/header.phtml") ?>

<img class="gameBackgroundImage" alt="<?= $game["title"] ?>" src="/images/games/<?= $gameBackgroundImage ?>">
<div class="main-container container game-detail">
  <h1><?= $game["title"] ?></h1>

  <section>

    <img alt="<?= $game["title"] ?>" src="/images/games/<?= $game["image"] ?>">
    <?= $game["details"] ?>
    <ul class="priceAndSupply">
      <li>
        <span class="tag">&euro; <?= $game["price"] ?></span>
      </li>
      <li>
        <a class="button" href="/cart/add/<?= $game["id"] ?>"><span class="lnr lnr-cart"></span>+</a>
      </li>
      <li>
        Voorraad: <?= $game["supply"] ?>
      </li>
    </ul>

    <h3>Details:</h3>
    <ul class="details">
      <li><strong>Platform</strong> <?= $game["platform"] ?></li>
      <li><strong>Developer</strong> <?= $game["developer"] ?></li>
      <li><strong>Publisher</strong> <?= $game["publisher"] ?></li>
      <li><strong>Gesproken</strong> <?= $game["languageSpoken"] ?></li>
      <li><strong>Geschreven</strong> <?= $game["languageText"] ?></li>
    </ul>
  </section>
</div>
<?php include("Partials/footer.phtml") ?>
