<?php include("Partials/header.phtml") ?>

<img class="gameBackgroundImage" alt="<?= $game["title"] ?>" src="/images/games/<?= $gameBackgroundImage ?>">
<div class="main-container container game-detail">
  <h1><?= $game["title"] ?></h1>

  <section>
    <img align="right" alt="<?= $game["title"] ?>" src="/images/games/<?= $game["image"] ?>">

      <?= $game["details"] ?>
    
    <span class="price">&euro; <?= $game["price"] ?></span>
    <a class="button" href="/cart/add/<?= $game["id"] ?>"><span class="lnr lnr-cart"></span></a>

    <h2>Details:</h2>
    <dl>
      <dt>Platform</dt>
      <dd><?= $game["platform"] ?></dd>

      <dt>Developer</dt>
      <dd><?= $game["developer"] ?></dd>

      <dt>Publisher</dt>
      <dd><?= $game["publisher"] ?></dd>

      <dt>Gesproken taal:</dt>
      <dd><?= $game["languageSpoken"] ?></dd>

      <dt>Geschreven taal:</dt>
      <dd><?= $game["languageText"] ?></dd>
    </dl>
  </section>
</div>
<?php include("Partials/footer.phtml") ?>
