<?= include("Partials/header.phtml") ?>
<div class="slider container">
    <figure>
        <a href="index.html">
            <img alt="Aanbieding Nintendo Switch" src="../images/slide_1200x500_Switch.jpg">
        </a>
        <a href="index.html">
            <img alt="Aanbieding days of play" src="../images/slide_1200x500_daysofplay.jpg">
        </a>
        <a href="index.html">
            <img alt="Pre order Red dead redemption 2" src="../images/slide_1200x500_RDR2.jpg">
        </a>
        <a href="index.html">
            <img alt="Aanbieding Nintendo Switch" src="../images/slide_1200x500_Switch.jpg">
        </a>
        <a href="index.html">
            <img alt="Aanbieding days of play" src="../images/slide_1200x500_daysofplay.jpg">
        </a>
    </figure>
</div>
<div class="main-container container">
    <aside>
        <form method="GET" action="/products">

            <fieldset>
                <legend>Platform</legend>
                <input type="checkbox" id="platformPs2" name="platform[ps2]" />
                <label for="platformPs2"><span>checkbox</span>Playstation 2</label>

                <input type="checkbox" id="platformPs3" name="platform[ps3]" />
                <label for="platformPs3"><span></span>Playstation 3</label>

                <input type="checkbox" id="platformPs4" name="platform[ps4]" />
                <label for="platformPs4"><span></span>Playstation 4</label>
            </fieldset>
            <fieldset>
                <legend>Genre</legend>
                <input type="checkbox" id="platformPs2" name="genre[action]" />
                <label for="platformPs2"><span></span>Playstation 2</label>

                <input type="checkbox" id="platformPs3" name="platform[ps3]" />
                <label for="platformPs3"><span></span>Playstation 3</label>

                <input type="checkbox" id="platformPs4" name="platform[ps4]" />
                <label for="platformPs4"><span></span>Playstation 4</label>
            </fieldset>
            <input type="submit" name="Filteren">
        </form>

    </aside>
    <main>
        <section>
            <h2>New collection</h2>
            <div class="article-collection">
                <article>
                    <div class="product-thumb">
                        <a href="#"><img alt="Secondary image of the article" class="product-back-img" src="http://via.placeholder.com/480x480/666666/898989"> <img alt="Primary image of the article" class="product-front-img" src="http://via.placeholder.com/480x480/000000/232323"></a>
                    </div>
                    <div class="product-info">
                        <h3><a href="#">Super Mario Bro's</a></h3>
                        <p>Asymmetrical waistcoat umami iPhone. Cold-pressed try-hard butcher prism. Intelligentsia fixie af, marfa vexillologist skateboard 90's cornhole twee viral gentrify kinfolk. Quinoa stumptown readymade woke chambray gentrify</p><span class="price">&euro; 75,00</span>
                    </div>
                    <div class="product-action">
                        <a class="button add-to-cart" href="#">Add to Cart</a> <a class="button" href="#"><span class="lnr lnr-heart"></span><span class="button-text">Add to Wishlist</span></a> <a class="button" href="#"><span class="lnr lnr-magnifier"></span><span class="button-text">Go to Article</span></a>
                    </div>
                </article>
                <article>
                    <div class="product-thumb">
                        <a href="#"><img alt="Secondary image of the article" class="product-back-img" src="http://via.placeholder.com/480x480/666666/898989"> <img alt="Primary image of the article" class="product-front-img" src="http://via.placeholder.com/480x480/000000/232323"></a>
                    </div>
                    <div class="product-info">
                        <h3><a href="#">Super Mario Bro's</a></h3>
                        <p>Asymmetrical waistcoat umami iPhone. Cold-pressed try-hard butcher prism. Intelligentsia fixie af, marfa vexillologist skateboard 90's cornhole twee viral gentrify kinfolk. Quinoa stumptown readymade woke chambray gentrify</p><span class="price">&euro; 75,00</span>
                    </div>
                    <div class="product-action">
                        <a class="button add-to-cart" href="#">Add to Cart</a> <a class="button" href="#"><span class="lnr lnr-heart"></span><span class="button-text">Add to Wishlist</span></a> <a class="button" href="#"><span class="lnr lnr-magnifier"></span><span class="button-text">Go to Article</span></a>
                    </div>
                </article>
                <article>
                    <div class="product-thumb">
                        <a href="#"><img alt="Secondary image of the article" class="product-back-img" src="http://via.placeholder.com/480x480/666666/898989"> <img alt="Primary image of the article" class="product-front-img" src="http://via.placeholder.com/480x480/000000/232323"></a>
                    </div>
                    <div class="product-info">
                        <h3><a href="#">Super Mario Bro's</a></h3>
                        <p>Asymmetrical waistcoat umami iPhone. Cold-pressed try-hard butcher prism. Intelligentsia fixie af, marfa vexillologist skateboard 90's cornhole twee viral gentrify kinfolk. Quinoa stumptown readymade woke chambray gentrify</p><span class="price">&euro; 75,00</span>
                    </div>
                    <div class="product-action">
                        <a class="button add-to-cart" href="#">Add to Cart</a> <a class="button" href="#"><span class="lnr lnr-heart"></span><span class="button-text">Add to Wishlist</span></a> <a class="button" href="#"><span class="lnr lnr-magnifier"></span><span class="button-text">Go to Article</span></a>
                    </div>
                </article>
                <article>
                    <div class="product-thumb">
                        <a href="#"><img alt="Secondary image of the article" class="product-back-img" src="http://via.placeholder.com/480x480/666666/898989"> <img alt="Primary image of the article" class="product-front-img" src="http://via.placeholder.com/480x480/000000/232323"></a>
                    </div>
                    <div class="product-info">
                        <h3><a href="#">Super Mario Bro's</a></h3>
                        <p>Asymmetrical waistcoat umami iPhone. Cold-pressed try-hard butcher prism. Intelligentsia fixie af, marfa vexillologist skateboard 90's cornhole twee viral gentrify kinfolk. Quinoa stumptown readymade woke chambray gentrify</p><span class="price">&euro; 75,00</span>
                    </div>
                    <div class="product-action">
                        <a class="button add-to-cart" href="#">Add to Cart</a> <a class="button" href="#"><span class="lnr lnr-heart"></span><span class="button-text">Add to Wishlist</span></a> <a class="button" href="#"><span class="lnr lnr-magnifier"></span><span class="button-text">Go to Article</span></a>
                    </div>
                </article>
                <article>
                    <div class="product-thumb">
                        <a href="#"><img alt="Secondary image of the article" class="product-back-img" src="http://via.placeholder.com/480x480/666666/898989"> <img alt="Primary image of the article" class="product-front-img" src="http://via.placeholder.com/480x480/000000/232323"></a>
                    </div>
                    <div class="product-info">
                        <h3><a href="#">Super Mario Bro's</a></h3>
                        <p>Asymmetrical waistcoat umami iPhone. Cold-pressed try-hard butcher prism. Intelligentsia fixie af, marfa vexillologist skateboard 90's cornhole twee viral gentrify kinfolk. Quinoa stumptown readymade woke chambray gentrify</p><span class="price">&euro; 75,00</span>
                    </div>
                    <div class="product-action">
                        <a class="button add-to-cart" href="#">Add to Cart</a> <a class="button" href="#"><span class="lnr lnr-heart"></span><span class="button-text">Add to Wishlist</span></a> <a class="button" href="#"><span class="lnr lnr-magnifier"></span><span class="button-text">Go to Article</span></a>
                    </div>
                </article>
            </div>
        </section>
        <section>
            <h2>Old collection</h2>
            <div class="article-collection">
                <article>
                    <div class="product-thumb">
                        <a href="#"><img alt="Secondary image of the article" class="product-back-img" src="http://via.placeholder.com/480x480/666666/898989"> <img alt="Primary image of the article" class="product-front-img" src="http://via.placeholder.com/480x480/000000/232323"></a>
                    </div>
                    <div class="product-info">
                        <h3><a href="#">Super Mario Bro's</a></h3>
                        <p>Asymmetrical waistcoat umami iPhone. Cold-pressed try-hard butcher prism. Intelligentsia fixie af, marfa vexillologist skateboard 90's cornhole twee viral gentrify kinfolk. Quinoa stumptown readymade woke chambray gentrify</p><span class="price">&euro; 75,00</span>
                    </div>
                    <div class="product-action">
                        <a class="button add-to-cart" href="#">Add to Cart</a> <a class="button" href="#"><span class="lnr lnr-heart"></span><span class="button-text">Add to Wishlist</span></a> <a class="button" href="#"><span class="lnr lnr-magnifier"></span><span class="button-text">Go to Article</span></a>
                    </div>
                </article>
                <article>
                    <div class="product-thumb">
                        <a href="#"><img alt="Secondary image of the article" class="product-back-img" src="http://via.placeholder.com/480x480/666666/898989"> <img alt="Primary image of the article" class="product-front-img" src="http://via.placeholder.com/480x480/000000/232323"></a>
                    </div>
                    <div class="product-info">
                        <h3><a href="#">Super Mario Bro's</a></h3>
                        <p>Asymmetrical waistcoat umami iPhone. Cold-pressed try-hard butcher prism. Intelligentsia fixie af, marfa vexillologist skateboard 90's cornhole twee viral gentrify kinfolk. Quinoa stumptown readymade woke chambray gentrify</p><span class="price">&euro; 75,00</span>
                    </div>
                    <div class="product-action">
                        <a class="button add-to-cart" href="#">Add to Cart</a> <a class="button" href="#"><span class="lnr lnr-heart"></span><span class="button-text">Add to Wishlist</span></a> <a class="button" href="#"><span class="lnr lnr-magnifier"></span><span class="button-text">Go to Article</span></a>
                    </div>
                </article>
                <article>
                    <div class="product-thumb">
                        <a href="#"><img alt="Secondary image of the article" class="product-back-img" src="http://via.placeholder.com/480x480/666666/898989"> <img alt="Primary image of the article" class="product-front-img" src="http://via.placeholder.com/480x480/000000/232323"></a>
                    </div>
                    <div class="product-info">
                        <h3><a href="#">Super Mario Bro's</a></h3>
                        <p>Asymmetrical waistcoat umami iPhone. Cold-pressed try-hard butcher prism. Intelligentsia fixie af, marfa vexillologist skateboard 90's cornhole twee viral gentrify kinfolk. Quinoa stumptown readymade woke chambray gentrify</p><span class="price">&euro; 75,00</span>
                    </div>
                    <div class="product-action">
                        <a class="button add-to-cart" href="#">Add to Cart</a> <a class="button" href="#"><span class="lnr lnr-heart"></span><span class="button-text">Add to Wishlist</span></a> <a class="button" href="#"><span class="lnr lnr-magnifier"></span><span class="button-text">Go to Article</span></a>
                    </div>
                </article>
                <article>
                    <div class="product-thumb">
                        <a href="#"><img alt="Secondary image of the article" class="product-back-img" src="http://via.placeholder.com/480x480/666666/898989"> <img alt="Primary image of the article" class="product-front-img" src="http://via.placeholder.com/480x480/000000/232323"></a>
                    </div>
                    <div class="product-info">
                        <h3><a href="#">Super Mario Bro's</a></h3>
                        <p>Asymmetrical waistcoat umami iPhone. Cold-pressed try-hard butcher prism. Intelligentsia fixie af, marfa vexillologist skateboard 90's cornhole twee viral gentrify kinfolk. Quinoa stumptown readymade woke chambray gentrify</p><span class="price">&euro; 75,00</span>
                    </div>
                    <div class="product-action">
                        <a class="button add-to-cart" href="#">Add to Cart</a> <a class="button" href="#"><span class="lnr lnr-heart"></span><span class="button-text">Add to Wishlist</span></a> <a class="button" href="#"><span class="lnr lnr-magnifier"></span><span class="button-text">Go to Article</span></a>
                    </div>
                </article>
                <article>
                    <div class="product-thumb">
                        <a href="#"><img alt="Secondary image of the article" class="product-back-img" src="http://via.placeholder.com/480x480/666666/898989"> <img alt="Primary image of the article" class="product-front-img" src="http://via.placeholder.com/480x480/000000/232323"></a>
                    </div>
                    <div class="product-info">
                        <h3><a href="#">Super Mario Bro's</a></h3>
                        <p>Asymmetrical waistcoat umami iPhone. Cold-pressed try-hard butcher prism. Intelligentsia fixie af, marfa vexillologist skateboard 90's cornhole twee viral gentrify kinfolk. Quinoa stumptown readymade woke chambray gentrify</p><span class="price">&euro; 75,00</span>
                    </div>
                    <div class="product-action">
                        <a class="button add-to-cart" href="#">Add to Cart</a> <a class="button" href="#"><span class="lnr lnr-heart"></span><span class="button-text">Add to Wishlist</span></a> <a class="button" href="#"><span class="lnr lnr-magnifier"></span><span class="button-text">Go to Article</span></a>
                    </div>
                </article>
            </div>
        </section>
    </main>
</div>
<?= include("Partials/footer.phtml") ?>
